### PR TITLE
Can record through microphone bluetooth

### PR DESCRIPTION
**Pull request by rezins**
And also can record background mode in iOS . Just add background mode 'Audio' in capabilities.

### CODE REVIEW

**Comment by appinteractive** [comment]
Any updates on that one? Background Recording would be awesome.

**Comment by harshmdr-devslane** [comment]
Any update here?
Please resolve conflicts

**Comment by rezins** [comment]
Really sorry, I've been busy past week. This package has been modified for personal purpose. I will fork again and add some features

**Comment by rezins** [comment]
Soon I pull request again.

**Comment by harshmdr-devslane** [comment]
we also need microphone bluetooth recording as well as background mode recording.

**Comment by rezins** [comment]
Sorry for taking couple of weeks. 
Please take a look [https://github.com/llfbandit/record/pull/284](url)

**Pull request closed without merging**
