### PR TITLE
Support: Background Isolate

### PR DESCRIPTION
**Pull request by v7lin**

### CODE REVIEW

**Comment by llfbandit** [comment]
How is it related to background isolation?
For what purpose? Recorder processes already in its own thread.

**Comment by v7lin** [comment]
you can try run record with android_alarm_manager

**Comment by v7lin** [comment]
it does not work when i call any method on background-isolate without ui(FlutterActivity).

**Comment by llfbandit** [comment]
It could work if you remove Activity aware feature. But I won't merge it.
This PR is a mess and diverge from the aim of the package.

**Comment by v7lin** [comment]
-_-!!! ...

**Comment by llfbandit** [comment]
In its current state, there's too many modifications unrelated to background recording.
It is really hard to find what is really modified to achieve the purpose.
Also, this should be optional and on par with iOS if possible.

**Pull request closed without merging**
