### PR TITLE
fix(macos): correct incorrect PCM16 Audio Stream data #336

### PR DESCRIPTION
**Pull request by ihdream72**
Incorrect buffer size for sending Streams and increasing the size

### CODE REVIEW

**Comment by ihdream72** [comment]
This is my first PR on Github.
Not sure if I did it right -_-

**Comment by llfbandit** [comment]
This is fine.
Can you confirm that iOS platform also works with this change?

**Comment by ihdream72** [comment]
I don't have an IOS phone, so I couldn't check it on IOS.
If you look at the record_darwin source, it is split between macos and ios and I only modified the code for macos. I don't think it will affect IOS.

**Comment by ihdream72** [comment]
I got an iphone and tested it out and it worked fine.
The way I tested was the same, I got the stream record with PCM16 and connected it to Google STT and it worked fine.

**Pull request merged**
